# Environment for querying MIMIC using Google BigQuery
# conda env create -f conda_env_gbq.yml
name: GBQ
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - nb_conda_kernels
  - jupyter_contrib_nbextensions
  - jupyterlab
  - pandas
  - ipywidgets
  - matplotlib
  - numpy
  - google-colab
  - google-cloud-bigquery
  - google-cloud-sdk
  - pandas-gbq
  - plotly
  - seaborn